### ISSUE TITLE
Help to build

### ISSUE THREAD

**Issue by mathkartel** [moon250/psi#3]
you can describe how i build this project?

**Comment by moon250** [comment]
Hi ! Because it is build as a web app with a php backend you can't actually build it. Instead, you can run in in the background in a docker container.
Just download/clone the repo on your machine and run the docker container in the background (docker-compose up -d)

You may see the configuration in the [docker-compose.yml](https://github.com/moon250/psi/blob/master/docker-compose.yml) file, and edit it as you like (if you don't want it to start with your computer for example, or if you want to change the port)

**Comment by mathkartel** [comment]
Oh yes, it's just that I would like to deploy on a shared server that doesn't have Docker in order to run some tests.

**Comment by moon250** [comment]
Just run a basic php server then ! Docker is just running a barebones apache php server under the hood ([Dockerfile](https://github.com/moon250/psi/blob/master/docker/php/Dockerfile) here) with ``php -S localhost:[port] -t public``

**Comment by mathkartel** [comment]
ohhh ok
